#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# sync_flags.sh
#
# Fetches all LaunchDarkly feature flags and generates:
#   1. imports.tf        — import blocks for every untracked flag
#   2. generated_flags.tf — full resource blocks (via terraform plan)
#
# Usage:
#   export LD_API_KEY=your-api-key
#   export LD_PROJECT_KEY=default          # optional, defaults to "default"
#   export LD_ENVIRONMENT_KEY=production   # optional, defaults to "production"
#   ./sync_flags.sh
# ---------------------------------------------------------------------------

set -euo pipefail

# ---------------------------------------------------------------------------
# Config — load from .env at project root (two levels up from devops/terraform)
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../../.env"

if [[ -f "$ENV_FILE" ]]; then
  echo "Loading credentials from $ENV_FILE"
  while IFS='=' read -r key value; do
    # Skip blank lines, comments, and lines without =
    [[ -z "$key" || "$key" == \#* || -z "$value" ]] && continue
    export "$key=$value"
  done < "$ENV_FILE"
else
  echo "Warning: .env not found at $ENV_FILE — falling back to environment variables"
fi

LD_API_KEY="${LD_API_KEY:?Error: LD_API_KEY not set in .env or environment}"
LD_PROJECT_KEY="${LD_PROJECT_KEY:-default}"
LD_ENVIRONMENT_KEY="${LD_ENVIRONMENT_KEY:-production}"
IMPORTS_FILE="imports.tf"
GENERATED_FILE="generated_flags.tf"
API_BASE="https://app.launchdarkly.com/api/v2"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
check_deps() {
  for cmd in curl jq terraform; do
    if ! command -v "$cmd" &>/dev/null; then
      echo "Error: '$cmd' is required but not installed." >&2
      exit 1
    fi
  done
}

# Convert a flag key like "enable-ai-chatbot" to a Terraform resource name
# like "enable_ai_chatbot"
to_resource_name() {
  echo "$1" | tr '-' '_' | tr '.' '_'
}

# Fetch all flags with pagination into a temp file (bash 3.2 compatible)
fetch_all_flags() {
  local offset=0
  local limit=100
  local tmp_file
  tmp_file=$(mktemp)

  echo "Fetching flags from LaunchDarkly (project: $LD_PROJECT_KEY)..." >&2

  while true; do
    response=$(curl -s \
      -H "Authorization: $LD_API_KEY" \
      "$API_BASE/flags/$LD_PROJECT_KEY?limit=$limit&offset=$offset")

    if echo "$response" | jq -e '.code' &>/dev/null; then
      echo "Error: LD API returned: $(echo "$response" | jq -r '.message // .code')" >&2
      exit 1
    fi

    echo "$response" | jq -r '.items[].key' >> "$tmp_file"
    total=$(echo "$response" | jq -r '.totalCount')
    count=$(echo "$response" | jq -r '.items | length')

    offset=$((offset + count))
    echo "  Fetched $offset / $total flags..." >&2

    if [[ $offset -ge $total ]]; then
      break
    fi
  done

  sort "$tmp_file"
  rm -f "$tmp_file"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
check_deps

cd "$(dirname "$0")"

# Fetch all flag keys into a temp file
TMP_KEYS=$(mktemp)
fetch_all_flags > "$TMP_KEYS"
FLAG_COUNT=$(wc -l < "$TMP_KEYS" | tr -d ' ')

echo ""
echo "Found $FLAG_COUNT flags. Generating $IMPORTS_FILE..."

# ---------------------------------------------------------------------------
# Generate imports.tf
# ---------------------------------------------------------------------------
cat > "$IMPORTS_FILE" <<'HEADER'
# ---------------------------------------------------------------------------
# imports.tf — AUTO-GENERATED by sync_flags.sh. DO NOT EDIT MANUALLY.
#
# Run: terraform plan -generate-config-out=generated_flags.tf
# Then: terraform apply
# Then move resources from generated_flags.tf into flags.tf and delete both
# this file and generated_flags.tf once apply succeeds.
# ---------------------------------------------------------------------------

HEADER

while IFS= read -r key; do
  [[ -z "$key" ]] && continue
  resource_name=$(to_resource_name "$key")
  cat >> "$IMPORTS_FILE" <<EOF
import {
  to = launchdarkly_feature_flag.${resource_name}
  id = "${LD_PROJECT_KEY}/${key}"
}

EOF
done < "$TMP_KEYS"

rm -f "$TMP_KEYS"
echo "Written: $IMPORTS_FILE ($FLAG_COUNT import blocks)"

# ---------------------------------------------------------------------------
# Write terraform.tfvars so terraform commands don't prompt for variables
# ---------------------------------------------------------------------------
cat > terraform.tfvars <<EOF
ld_api_key         = "$LD_API_KEY"
ld_project_key     = "$LD_PROJECT_KEY"
ld_environment_key = "$LD_ENVIRONMENT_KEY"
EOF
echo "Written: terraform.tfvars"

# ---------------------------------------------------------------------------
# Run terraform init if .terraform directory doesn't exist
# ---------------------------------------------------------------------------
if [[ ! -d ".terraform" ]]; then
  echo ""
  echo "Running terraform init..."
  terraform init
fi

# ---------------------------------------------------------------------------
# Generate resource blocks
# ---------------------------------------------------------------------------
echo ""
echo "Running: terraform plan -generate-config-out=$GENERATED_FILE"
echo "(This calls the LD API for each flag — may take a moment...)"
echo ""

terraform plan -generate-config-out="$GENERATED_FILE"

echo ""
echo "Done!"
echo ""
echo "Next steps:"
echo "  1. Review $GENERATED_FILE"
echo "  2. Run: terraform apply"
echo "  3. Move resources from $GENERATED_FILE into flags.tf"
echo "  4. Delete $IMPORTS_FILE and $GENERATED_FILE"
